[build]
  publish = "/"
  command = ""  # No build command needed for simple HTML/CSS site

# Redirect and rewrite rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com https://cdnjs.cloudflare.com; img-src 'self' data: https: placehold.co; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https:; media-src 'self' https:; object-src 'none'; child-src 'none';"
